name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ROS
      run: |
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        sudo apt-get update
        sudo apt-get install -y ros-melodic-ros-base ros-melodic-actionlib
        source /opt/ros/melodic/setup.bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python3 -m pytest